<a href="https://colab.research.google.com/github/Asifkhan154/Asifkhan15/blob/main/prectish_pandas_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

costomized index -> apne jarurato ke hisab se jo kuch badla jaye use ham  coutomized index khate  hai

In [ ]:
Series_Scalar = pd.Series(2, index = ['a','b','c','d','e','f'])
print(Series_Scalar)

a    2
b    2
c    2
d    2
e    2
f    2
dtype: int64

In [ ]:
type(Series_Scalar)

pandas.core.series.Series

default index=> phle s majid index ko default index khate hai

In [ ]:
data=[10,20,30,40,50]
Series_list=pd.Series(data)
print(Series_list)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
type(Series_list)

pandas.core.series.Series

In [ ]:
Series_list.shape

(5,)

Load dataet

In [ ]:
coustomars_df = pd.read_excel('/content/customers.xlsx')
products_df = pd.read_excel('/content/products.xlsx')
purchases_df = pd.read_excel('/content/purchases.xlsx')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
coustomars_df.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

In [ ]:
coustomars_df.shape

(1000, 11)

In [ ]:
coustomars_df.size

11000

In [ ]:
type(coustomars_df)

pandas.core.frame.DataFrame

attribeuit in series > yeh jankari deta hai ki kiatne column hai kitne row hia

In [ ]:
data=['NewDelahi','WashingtonDc','London','paries']
index=['india','USA','UK','France']
Series_capital_country = pd.Series(data,index=index)
Series_capital_country

india        NewDelahi
USA       WashingtonDc
UK              London
France          paries
dtype: object

In [ ]:
type(Series_capital_country)

pandas.core.series.Series

In [ ]:
Series_capital_country.index

Index(['india', 'USA', 'UK', 'France'], dtype='object')

In [ ]:
Series_capital_country.values

array(['NewDelahi', 'WashingtonDc', 'London', 'paries'], dtype=object)

In [ ]:
Series_capital_country.dtype

dtype('O')

In [ ]:
Series_capital_country.shape

(4,)

In [ ]:
Series_capital_country.is_unique

True

In [ ]:
Series_capital_country.ndim

1

Method in series=> joden ka aam kerta hai  jise datafram df ya series ets jodne ka aam krete hai

In [ ]:
marks = [85,90,65,97,97]
students = ['Sanjay','Arun','Saurabh','Asif','Mariyam']
Series_students_marks = pd.Series(marks,index=students)
print(Series_students_marks)

Sanjay     85
Arun       90
Saurabh    65
Asif       97
Mariyam    97
dtype: int64

In [ ]:
Series_students_marks.head(3)

Sanjay     85
Arun       90
Saurabh    65
dtype: int64

In [ ]:
# bottom ka student ke name chaiye

Series_students_marks.tail(3)

Saurabh    65
Asif       97
Mariyam    97
dtype: int64

summary of the describe the staics

In [ ]:
# data ko sumrise krenge
Series_students_marks.describe()

count     5.000000
mean     86.800000
std      13.198485
min      65.000000
25%      85.000000
50%      90.000000
75%      97.000000
max      97.000000
dtype: float64

In [ ]:
Series_students_marks.value_counts()

97    2
85    1
90    1
65    1
Name: count, dtype: int64

In [ ]:
# sort_value => asanding order me rhakna 3>6 chote se bada
Series_students_marks.sort_values()

Saurabh    65
Sanjay     85
Arun       90
Asif       97
Mariyam    97
dtype: int64

In [ ]:
# desending order chiye 3<5 bade se chota numbers cahiye

Series_students_marks.sort_values(ascending=False)

Mariyam    97
Asif       97
Arun       90
Sanjay     85
Saurabh    65
dtype: int64

drop[removing]

In [ ]:
Series_students_marks.drop('Saurabh')

Sanjay     85
Arun       90
Asif       97
Mariyam    97
dtype: int64

In [ ]:
Series_students_marks

Sanjay     85
Arun       90
Asif       97
Mariyam    97
dtype: int64

In [ ]:
Series_students_marks.drop('Saurabh',inplace=True)

KeyError: "['Saurabh'] not found in axis"

In [ ]:
Series_students_marks

Sanjay     85
Arun       90
Asif       97
Mariyam    97
dtype: int64

In [ ]:
print(Series_students_marks.drop('Sanjay'))

Arun       90
Asif       97
Mariyam    97
dtype: int64

In [ ]:
Series_students_marks

Sanjay     85
Arun       90
Asif       97
Mariyam    97
dtype: int64

In [ ]:
Series_students_marks.drop('Sanjay',inplace=True)

In [ ]:
Series_students_marks

Arun       90
Asif       97
Mariyam    97
dtype: int64

In [ ]:
Series_students_marks.sort_values(ascending=False)

Asif       97
Mariyam    97
Arun       90
dtype: int64

In [ ]:
Series_students_marks.tail(2)

Asif       97
Mariyam    97
dtype: int64

In [ ]:
Series_students_marks.sort_values(ascending=False).head(2)

Asif       97
Mariyam    97
dtype: int64

missing values-> eska mtlab hota hai NaN valuues ko 0 se relace ker dena uya or kisis alues ka name rlh an hota ha

In [ ]:
missing_values = coustomars_df.isnull().sum()
print(missing_values)

id                 0
first_name         0
last_name          0
email            122
gender            43
street_num       262
street_name       37
street_suffix     37
city              79
state             80
postcode         157
dtype: int64

mathmatical opraters in series=> ye data fram ko ya series ke ander ko multiply kerne me use hota hai

example me  => NaN =  not avilabel number = missing values

In [ ]:
Series_1 =  pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
Series_2 = pd.Series([10,20,30,40,50],index=['z','y','a','c','e'])
print(Series_1)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
print(Series_2)

z    10
y    20
a    30
c    40
e    50
dtype: int64

In [ ]:
result_addition=Series_1-Series_2
print(result_addition)

a   -29.0
b     NaN
c   -37.0
d     NaN
e   -45.0
y     NaN
z     NaN
dtype: float64

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,7,9])
result=arr1+arr2
print(result)

ValueError: operands could not be broadcast together with shapes (5,) (3,)

In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,7,9,11,16])
result=arr1+arr2
print(result)

[ 5  9 12 15 21]

In [ ]:
result=result_addition.fillna(0)
print(result)

a   -29.0
b     0.0
c   -37.0
d     0.0
e   -45.0
y     0.0
z     0.0
dtype: float64

In [ ]:
result_addition_dropped=result_addition.dropna()
print(result_addition_dropped)

a   -29.0
c   -37.0
e   -45.0
dtype: float64

multipaction

In [ ]:
result_multiplaction= Series_1*Series_2
print(result_multiplaction)

a     30.0
b      NaN
c    120.0
d      NaN
e    250.0
y      NaN
z      NaN
dtype: float64

In [ ]:
result_multiplaction_dropped=result_multiplaction.dropna()
print(result_multiplaction_dropped)

a     30.0
c    120.0
e    250.0
dtype: float64

In [ ]:
result_multiplaction=result_multiplaction.fillna(1)
print(result_multiplaction)

a     30.0
b      1.0
c    120.0
d      1.0
e    250.0
y      1.0
z      1.0
dtype: float64

divisionn two series

In [ ]:
result_division=Series_1/Series_2
print(result_division)

a    0.033333
b         NaN
c    0.075000
d         NaN
e    0.100000
y         NaN
z         NaN
dtype: float64

In [ ]:
result_division_dropped=result_division.dropna()
print(result_division_dropped)

a    0.033333
c    0.075000
e    0.100000
dtype: float64

In [ ]:
result_division.shape

(7,)

In [ ]:
result_division.describe()

count    3.000000
mean     0.069444
std      0.033679
min      0.033333
25%      0.054167
50%      0.075000
75%      0.087500
max      0.100000
dtype: float64

data frame

In [ ]:
coustomars_df.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

In [ ]:
purchases_df.head()

   id           purch_date  customer_num  product_num  amount     paid
0   1  2019-01-03 00:00:00           823           27      12  $568.92
1   2  2019-01-03 00:00:00           606           28      14  $395.36
2   3  2019-01-03 00:00:00           955            9      17  $510.17
3   4  2019-01-03 00:00:00           577           19       3   $68.49
4   5  2019-01-03 00:00:00           429            8      18  $759.42

In [ ]:
products_df.head()

   Unnamed: 0  id                           product    cost   company
0           0   1              Liners - Baking Cups   $6.36  Skipfire
1           1   2        Nori Sea Weed - Gold Label  $85.74   Dynazzy
2           2   3                Bar Bran Honey Nut  $65.40      Ntag
3           3   4        Soup - Campbells Beef Stew  $68.16  Photojam
4           4   5  Wine - Shiraz Wolf Blass Premium  $87.39      Eare

droped columns named below 'unmaed:0' from products_df or purchases_df

In [ ]:
purchases_df.drop(columns=['Unnamed: 0'],inplace=True,errors='ignore')
products_df.drop(columns=['Unnamed: 0'],inplace=True)

In [ ]:
purchases_df.head()

   id           purch_date  customer_num  product_num  amount     paid
0   1  2019-01-03 00:00:00           823           27      12  $568.92
1   2  2019-01-03 00:00:00           606           28      14  $395.36
2   3  2019-01-03 00:00:00           955            9      17  $510.17
3   4  2019-01-03 00:00:00           577           19       3   $68.49
4   5  2019-01-03 00:00:00           429            8      18  $759.42

In [ ]:
products_df.head()

   id                           product    cost   company
0   1              Liners - Baking Cups   $6.36  Skipfire
1   2        Nori Sea Weed - Gold Label  $85.74   Dynazzy
2   3                Bar Bran Honey Nut  $65.40      Ntag
3   4        Soup - Campbells Beef Stew  $68.16  Photojam
4   5  Wine - Shiraz Wolf Blass Premium  $87.39      Eare

iloc vs loc => data frame me slaicing krene ke liye ya selction kerne ke lie  hota hai use hota hai

In [ ]:
# iloc data frame me slaicing krene ke liye ya selction kerne ke lie  hota hai use hota hai
coustomars_df

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

In [ ]:
coustomars_df.shape

(1000, 11)

In [ ]:
# defult and positinal index
# ending ineddx is inclusive

coustomars_df.iloc[4:11,1:3]

    first_name   last_name
4      Mikaela    Althorpe
5    Magdalena      Cullip
6     Marietta      Heball
7         Tine   McSperrin
8   Enrichetta  de Villier
9         Sari     Poulden
10      Natale     Martina

In [ ]:
# labbled or coutomized indexes
# ending index is enclusive

coustomars_df.loc[4:10,['first_name','last_name']]

    first_name   last_name
4      Mikaela    Althorpe
5    Magdalena      Cullip
6     Marietta      Heball
7         Tine   McSperrin
8   Enrichetta  de Villier
9         Sari     Poulden
10      Natale     Martina

In [ ]:
coustomars_df.iloc[11:51,1:5]

   first_name      last_name                          email  gender
11       Noni     Norrington      nnorringtonb@netvibes.com  Female
12      Mikol        MacWhan            mmacwhanc@patch.com    Male
13       Deny        Thraves              dthravesd@ibm.com  Female
14       Fara       Petegrew            fpetegrewe@ebay.com  Female
15      Jodie  De Cristoforo         jdecristoforof@mac.com    Male
16       Tobi        Dewicke        tdewickeg@hostgator.com  Female
17   Reinhold      Woolforde             rwoolfordeh@cbc.ca    Male
18     Fredek          Foley                ffoleyi@bbb.org    Male
19     Rubina       Hustings       rhustingsj@wikimedia.org  Female
20      Karim        Woosnam            kwoosnamk@ifeng.com    Male
21    Woodrow          Fidoe    wfidoel@creativecommons.org    Male
22    Loralie        Normand              lnormandm@usa.gov  Female
23     Danita      Cleynaert        dcleynaertn@t-online.de  Female
24     Tomlin      Massinger                            NaN    Male
25   Franklin         Goodge          fgoodgep@mapquest.com    Male
26    Harlene         Rameau       hrameauq@squarespace.com  Female
27    Brander      Quinnelly      bquinnellyr@shinystat.com    Male
28     Jeanna        Bruntje        jbruntjes@tuttocitta.it  Female
29     Ardyth           Zack           azackt@wordpress.com  Female
30      Steve      Pantridge                            NaN    Male
31       Brit          Nouch              bnouchv@yahoo.com  Female
32      Caril       Barnsley      cbarnsleyw@bravesites.com  Female
33   Rosalynd        Dyerson         rdyersonx@geocities.jp  Female
34     Griffy         Sonley        gsonleyy@deviantart.com    Male
35     Ernest          Armal        earmalz@dailymail.co.uk    Male
36    Elspeth         Mendus            emendus10@ocn.ne.jp  Female
37    Clarita        Bussons     cbussons11@marketwatch.com  Female
38  Stanislas         Hacaud                            NaN    Male
39     Melvyn        Seifert     mseifert13@photobucket.com    Male
40       Ruby          Plott                rplott14@un.org    Male
41     Nollie         Salter      nsalter15@fastcompany.com    Male
42   Bendicty         Sunnex           bsunnex16@elpais.com    Male
43    Garrett        Bartram             gbartram17@sun.com    Male
44      Berna      Longhurst      blonghurst18@geocities.jp  Female
45      Edmon       Elsegood  eelsegood19@ezinearticles.com    Male
46      Burch        Issacov             bissacov1a@tiny.cc    Male
47       Rori         Clashe           rclashe1b@smh.com.au  Female
48      Flinn         Hoston                            NaN    Male
49  Claudette         Ivatts                            NaN  Female
50     Correy          Raatz               craatz1e@ihg.com    Male

In [ ]:
coustomars_df.loc[10:15,['first_name','gender','email']]

   first_name  gender                      email
10     Natale    Male    nmartinaa@wordpress.com
11       Noni  Female  nnorringtonb@netvibes.com
12      Mikol    Male        mmacwhanc@patch.com
13       Deny  Female          dthravesd@ibm.com
14       Fara  Female        fpetegrewe@ebay.com
15      Jodie    Male     jdecristoforof@mac.com

filtering data set

In [ ]:
male_coustomars=coustomars_df[coustomars_df['gender']=='Male']
male_coustomars

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
10,11,Natale,Martina,nmartinaa@wordpress.com,Male,221.0,Sauthoff,Pass,Bradenton,Florida,34205.0
12,13,Mikol,MacWhan,mmacwhanc@patch.com,Male,9.0,Eagle Crest,Center,Bronx,New York,10469.0
...,...,...,...,...,...,...,...,...,...,...,...
984,985,Tailor,Sealeaf,tsealeafrc@irs.gov,Male,NaN,Summer Ridge,Pass,Beaufort,South Carolina,29905.0
986,987,Eric,Mountford,emountfordre@blogspot.com,Male,NaN,6th,Court,Las Vegas,Nevada,89125.0
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

In [ ]:
purchases_df.head()

   id           purch_date  customer_num  product_num  amount     paid
0   1  2019-01-03 00:00:00           823           27      12  $568.92
1   2  2019-01-03 00:00:00           606           28      14  $395.36
2   3  2019-01-03 00:00:00           955            9      17  $510.17
3   4  2019-01-03 00:00:00           577           19       3   $68.49
4   5  2019-01-03 00:00:00           429            8      18  $759.42

In [ ]:

purchases_df.head()

   id           purch_date  customer_num  product_num  amount     paid
0   1  2019-01-03 00:00:00           823           27      12  $568.92
1   2  2019-01-03 00:00:00           606           28      14  $395.36
2   3  2019-01-03 00:00:00           955            9      17  $510.17
3   4  2019-01-03 00:00:00           577           19       3   $68.49
4   5  2019-01-03 00:00:00           429            8      18  $759.42

access only 2,3 and 4th row or 2 products or piad columns

In [ ]:
purchases_df.loc[2:4,['product_num','paid']]

   product_num     paid
2            9  $510.17
3           19   $68.49
4            8  $759.42

In [ ]:
purchases_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            6000 non-null   int64
 1   purch_date    6000 non-null   object
 2   customer_num  6000 non-null   int64
 3   product_num   6000 non-null   int64
 4   amount        6000 non-null   int64
 5   paid          6000 non-null   object
dtypes: int64(4), object(2)
memory usage: 281.4+ KB

Renaming rows labels of data framing=> isme rows or columns ka name change keren ke liya use hota hai

In [ ]:
coustomars_df.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

rename my data frame in  a given data frame

In [ ]:
coustomars_df.rename(index={0:'first_coustomars'},inplace=True)
coustomars_df

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
first_coustomars,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

In [ ]:
purchases_df.rename(index={'first_coustomars':0},inplace=True)
purchases_df

        id           purch_date  customer_num  product_num  amount     paid
0        1  2019-01-03 00:00:00           823           27      12  $568.92
1        2  2019-01-03 00:00:00           606           28      14  $395.36
2        3  2019-01-03 00:00:00           955            9      17  $510.17
3        4  2019-01-03 00:00:00           577           19       3   $68.49
4        5  2019-01-03 00:00:00           429            8      18  $759.42
...    ...                  ...           ...          ...     ...      ...
5995  5996           06/20/2019           893           33       5  $411.10
5996  5997           06/20/2019           566           23      11  $178.97
5997  5998           06/20/2019           114           19       9  $205.47
5998  5999           06/20/2019           404           11      20  $429.40
5999  6000           06/20/2019            88           57       4  $274.52

[6000 rows x 6 columns]

In [ ]:
coustomars_df.rename(columns={'street_name':'street_address'},inplace=True)
coustomars_df

,id,first_name,last_name,email,gender,street_num,street_address,street_suffix,city,state,postcode
first_coustomars,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

finding the unique valus

In [ ]:
unique_gender=coustomars_df['gender'].unique()
unique_gender

array(['Male', 'Female', nan], dtype=object)

counnts of unique values

In [ ]:
unique_gender_count=coustomars_df['gender'].unique()
unique_gender_count

array(['Male', 'Female', nan], dtype=object)

type conversion off columns

In [ ]:
purchases_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6000 entries, 0 to 5999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            6000 non-null   int64
 1   purch_date    6000 non-null   object
 2   customer_num  6000 non-null   int64
 3   product_num   6000 non-null   int64
 4   amount        6000 non-null   int64
 5   paid          6000 non-null   object
dtypes: int64(4), object(2)
memory usage: 457.2+ KB

In [ ]:
purchases_df['purch_date']=pd.to_datetime(purchases_df['purch_date'])
purchases_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6000 entries, 0 to 5999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            6000 non-null   int64
 1   purch_date    6000 non-null   datetime64[ns]
 2   customer_num  6000 non-null   int64
 3   product_num   6000 non-null   int64
 4   amount        6000 non-null   int64
 5   paid          6000 non-null   object
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 457.2+ KB

In [ ]:
purchases_df['amount']=purchases_df['amount'].astype('float')
purchases_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6000 entries, 0 to 5999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            6000 non-null   int64
 1   purch_date    6000 non-null   datetime64[ns]
 2   customer_num  6000 non-null   int64
 3   product_num   6000 non-null   int64
 4   amount        6000 non-null   float64
 5   paid          6000 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 457.2+ KB

In [ ]:
purchases_df['paid']=purchases_df['paid'].str.replace('[\$]','',regex=True)
purchases_df

<>:1: SyntaxWarning: invalid escape sequence '\$'
<>:1: SyntaxWarning: invalid escape sequence '\$'
/tmp/ipykernel_12799/22686954.py:1: SyntaxWarning: invalid escape sequence '\$'
  purchases_df['paid']=purchases_df['paid'].str.replace('[\$]','',regex=True)

        id purch_date  customer_num  product_num  amount    paid
0        1 2019-01-03           823           27    12.0  568.92
1        2 2019-01-03           606           28    14.0  395.36
2        3 2019-01-03           955            9    17.0  510.17
3        4 2019-01-03           577           19     3.0   68.49
4        5 2019-01-03           429            8    18.0  759.42
...    ...        ...           ...          ...     ...     ...
5995  5996 2019-06-20           893           33     5.0  411.10
5996  5997 2019-06-20           566           23    11.0  178.97
5997  5998 2019-06-20           114           19     9.0  205.47
5998  5999 2019-06-20           404           11    20.0  429.40
5999  6000 2019-06-20            88           57     4.0  274.52

[6000 rows x 6 columns]

In [ ]:
purchases_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6000 entries, 0 to 5999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            6000 non-null   int64
 1   purch_date    6000 non-null   datetime64[ns]
 2   customer_num  6000 non-null   int64
 3   product_num   6000 non-null   int64
 4   amount        6000 non-null   float64
 5   paid          6000 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 457.2+ KB

In [ ]:
purchases_df['paid'] = purchases_df['paid'].str.replace(',', '', regex=True)
purchases_df['paid'] = purchases_df['paid'].astype('float')
purchases_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6000 entries, 0 to 5999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            6000 non-null   int64
 1   purch_date    6000 non-null   datetime64[ns]
 2   customer_num  6000 non-null   int64
 3   product_num   6000 non-null   int64
 4   amount        6000 non-null   float64
 5   paid          6000 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(3)
memory usage: 457.2 KB

In [ ]:
products_df.head()

   Unnamed: 0  id                           product    cost   company
0           0   1              Liners - Baking Cups   $6.36  Skipfire
1           1   2        Nori Sea Weed - Gold Label  $85.74   Dynazzy
2           2   3                Bar Bran Honey Nut  $65.40      Ntag
3           3   4        Soup - Campbells Beef Stew  $68.16  Photojam
4           4   5  Wine - Shiraz Wolf Blass Premium  $87.39      Eare

In [ ]:
products_df['cost']=products_df['cost'].str.replace('[$]','',regex=True)
products_df

    Unnamed: 0  id                             product   cost       company
0            0   1                Liners - Baking Cups   6.36      Skipfire
1            1   2          Nori Sea Weed - Gold Label  85.74       Dynazzy
2            2   3                  Bar Bran Honey Nut  65.40          Ntag
3            3   4          Soup - Campbells Beef Stew  68.16      Photojam
4            4   5    Wine - Shiraz Wolf Blass Premium  87.39          Eare
5            5   6  Wine - White, Riesling, Semi - Dry  99.22      Livepath
6            6   7                        Brandy - Bar  13.83          Oloo
7            7   8                      Onions - White  42.19          Oozz
8            8   9         Lettuce - Baby Salad Greens  30.01        Meevee
9            9  10                Sambuca - Ramazzotti  88.99      Livepath
10          10  11                Coffee - Decafenated  21.47        Meezzy
11          11  12             Lamb Leg - Bone - In Nz  42.56     Photofeed
12          12  13                Lettuce - Spring Mix  19.90  Twitterworks
13          13  14              Cookies Oatmeal Raisin  99.40       Dynabox
14          14  15              Cookies Oatmeal Raisin  14.13          Vitz
15          15  16                   Sausage - Chorizo  55.45           NaN
16          16  17                     Glaze - Apricot  33.78    Browsezoom
17          17  18                           Squid Ink  56.33         Aibox
18          18  19               Loaf Pan - 2 Lb, Foil  22.83   Brainsphere
19          19  20        Bagel - Everything Presliced  87.05        Trunyx
20          20  21          Bagel - Whole White Sesame  90.48      Realcube
21          21  22                 Scotch - Queen Anne  60.26           NaN
22          22  23                Puree - Blackcurrant  16.27       Zoombox
23          23  24               Bread - Bagels, Plain  31.26          Vitz
24          24  25               Snapple Raspberry Tea  73.70       Innojam
25          25  26               Sour Puss - Tangerine  84.20       Skinder
26          26  27                    Spaghetti Squash  47.41           NaN
27          27  28         Wine - Niagara,vqa Reisling  28.24           NaN
28          28  29                Iced Tea Concentrate  59.23     Photolist
29          29  30                         Fuji Apples  22.96       Cogibox
30          30  31      Wine - Carmenere Casillero Del  55.77          Ntag
31          31  32                Container Clear 8 Oz  92.33          Muxo
32          32  33                         Duck - Legs  82.22       Voonder
33          33  34            Muffin Hinge Container 6  99.54        Skyble
34          34  35          Pie Box - Cello Window 2.5  95.68      Linkbuzz
35          35  36              Bread - English Muffin  13.83         Quatz
36          36  37    Chocolate - Sugar Free Semi Choc  61.99     Realpoint
37          37  38                   Pate - Peppercorn  21.98         Mynte
38          38  39             Triple Sec - Mcguinness  37.45         Oodoo
39          39  40                  Pepper - Cubanelle  79.31       Cogibox
40          40  41                      Squash - Acorn  65.35         Meemm
41          41  42                  Sauce - Demi Glace  87.51      Wordware
42          42  43                   Pail For Lid 1537  40.69      Edgeclub
43          43  44                        Foam Tray S2  30.67  Jabbersphere
44          44  45                        Shark - Loin  45.77  Thoughtstorm
45          45  46            Aromat Spice / Seasoning  61.34           NaN
46          46  47                       Tobasco Sauce  48.32    Browsezoom
47          47  48           Apple - Delicious, Golden  36.67         Skiba
48          48  49                         Lamb - Rack  62.60         Gevee
49          49  50              Silicone Paper 16.5x24  63.98    Babbleopia
50          50  51               Ecolab - Power Fusion  75.32      Fliptune
51          51  52          Soup - Knorr, Country Bean  98.74        Eimbee
52          52  53            Chicken - Thigh, Bone In  74.06   Topiclounge
53          53  54      Plate - Foam, Bread And Butter  37.79     Flipstorm
54          54  55                     Beef - Bresaola   8.55      Digitube
55          55  56                       Peach - Fresh  20.53         Zazio
56          56  57                 Muffin Hinge - 211n  68.63      Fanoodle
57          57  58                  Bar Bran Honey Nut  73.05        Yakijo
58          58  59       Nut - Almond, Blanched, Whole  74.28         Eazzy
59          59  60            Table Cloth 90x90 Colour  41.22         Quinu

In [ ]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  60 non-null     int64
 1   id          60 non-null     int64
 2   product     60 non-null     object
 3   cost        60 non-null     object
 4   company     55 non-null     object
dtypes: int64(2), object(3)
memory usage: 2.5+ KB

In [ ]:
products_df['cost']=products_df['cost'].str.replace(',','',regex=True)
products_df['cost']=products_df['cost'].astype('float')
products_df

    Unnamed: 0  id                             product   cost       company
0            0   1                Liners - Baking Cups   6.36      Skipfire
1            1   2          Nori Sea Weed - Gold Label  85.74       Dynazzy
2            2   3                  Bar Bran Honey Nut  65.40          Ntag
3            3   4          Soup - Campbells Beef Stew  68.16      Photojam
4            4   5    Wine - Shiraz Wolf Blass Premium  87.39          Eare
5            5   6  Wine - White, Riesling, Semi - Dry  99.22      Livepath
6            6   7                        Brandy - Bar  13.83          Oloo
7            7   8                      Onions - White  42.19          Oozz
8            8   9         Lettuce - Baby Salad Greens  30.01        Meevee
9            9  10                Sambuca - Ramazzotti  88.99      Livepath
10          10  11                Coffee - Decafenated  21.47        Meezzy
11          11  12             Lamb Leg - Bone - In Nz  42.56     Photofeed
12          12  13                Lettuce - Spring Mix  19.90  Twitterworks
13          13  14              Cookies Oatmeal Raisin  99.40       Dynabox
14          14  15              Cookies Oatmeal Raisin  14.13          Vitz
15          15  16                   Sausage - Chorizo  55.45           NaN
16          16  17                     Glaze - Apricot  33.78    Browsezoom
17          17  18                           Squid Ink  56.33         Aibox
18          18  19               Loaf Pan - 2 Lb, Foil  22.83   Brainsphere
19          19  20        Bagel - Everything Presliced  87.05        Trunyx
20          20  21          Bagel - Whole White Sesame  90.48      Realcube
21          21  22                 Scotch - Queen Anne  60.26           NaN
22          22  23                Puree - Blackcurrant  16.27       Zoombox
23          23  24               Bread - Bagels, Plain  31.26          Vitz
24          24  25               Snapple Raspberry Tea  73.70       Innojam
25          25  26               Sour Puss - Tangerine  84.20       Skinder
26          26  27                    Spaghetti Squash  47.41           NaN
27          27  28         Wine - Niagara,vqa Reisling  28.24           NaN
28          28  29                Iced Tea Concentrate  59.23     Photolist
29          29  30                         Fuji Apples  22.96       Cogibox
30          30  31      Wine - Carmenere Casillero Del  55.77          Ntag
31          31  32                Container Clear 8 Oz  92.33          Muxo
32          32  33                         Duck - Legs  82.22       Voonder
33          33  34            Muffin Hinge Container 6  99.54        Skyble
34          34  35          Pie Box - Cello Window 2.5  95.68      Linkbuzz
35          35  36              Bread - English Muffin  13.83         Quatz
36          36  37    Chocolate - Sugar Free Semi Choc  61.99     Realpoint
37          37  38                   Pate - Peppercorn  21.98         Mynte
38          38  39             Triple Sec - Mcguinness  37.45         Oodoo
39          39  40                  Pepper - Cubanelle  79.31       Cogibox
40          40  41                      Squash - Acorn  65.35         Meemm
41          41  42                  Sauce - Demi Glace  87.51      Wordware
42          42  43                   Pail For Lid 1537  40.69      Edgeclub
43          43  44                        Foam Tray S2  30.67  Jabbersphere
44          44  45                        Shark - Loin  45.77  Thoughtstorm
45          45  46            Aromat Spice / Seasoning  61.34           NaN
46          46  47                       Tobasco Sauce  48.32    Browsezoom
47          47  48           Apple - Delicious, Golden  36.67         Skiba
48          48  49                         Lamb - Rack  62.60         Gevee
49          49  50              Silicone Paper 16.5x24  63.98    Babbleopia
50          50  51               Ecolab - Power Fusion  75.32      Fliptune
51          51  52          Soup - Knorr, Country Bean  98.74        Eimbee
52          52  53            Chicken - Thigh, Bone In  74.06   Topiclounge
53          53  54      Plate - Foam, Bread And Butter  37.79     Flipstorm
54          54  55                     Beef - Bresaola   8.55      Digitube
55          55  56                       Peach - Fresh  20.53         Zazio
56          56  57                 Muffin Hinge - 211n  68.63      Fanoodle
57          57  58                  Bar Bran Honey Nut  73.05        Yakijo
58          58  59       Nut - Almond, Blanched, Whole  74.28         Eazzy
59          59  60            Table Cloth 90x90 Colour  41.22         Quinu

In [ ]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  60 non-null     int64
 1   id          60 non-null     int64
 2   product     60 non-null     object
 3   cost        60 non-null     object
 4   company     55 non-null     object
dtypes: int64(2), object(3)
memory usage: 2.5+ KB

concatenation=> do allag allag data fram ko jidne ke liye use hota hai

In [ ]:
# concatenate along rows=axise=0
# roews ko ek ke baad ek jodte jana

In [ ]:
# concnate along columns =(axise=1)
# eska matlab hai ki columnns ko ek ke baad ek jodte jana

In [ ]:
coustomars_df.shape

(1000, 11)

In [ ]:
products_df.shape

(60, 5)

In [ ]:
purchases_df.shape

(6000, 7)

In [ ]:
# dodno data ko jodna hai

combined_df=pd.concat([coustomars_df,purchases_df,products_df])
combined_df

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Unnamed: 0,purch_date,customer_num,product_num,amount,paid,product,cost,company
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,Peach - Fresh,$20.53,Zazio
56,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.0,NaN,NaN,NaN,NaN,NaN,Muffin Hinge - 211n,$68.63,Fanoodle
57,58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.0,NaN,NaN,NaN,NaN,NaN,Bar Bran Honey Nut,$73.05,Yakijo
58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.0,NaN,NaN,NaN,NaN,NaN,"Nut - Almond, Blanched, Whole",$74.28,Eazzy
59,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0,NaN,NaN,NaN,NaN,NaN,Table Cloth 90x90 Colour,$41.22,Quinu

In [ ]:
coustomars_df.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

In [ ]:
purchases_df.head()

,Unnamed: 0,id,purch_date,customer_num,product_num,amount,paid
0,0,1,2019-01-03 00:00:00,823,27,12,$568.92
1,1,2,2019-01-03 00:00:00,606,28,14,$395.36
2,2,3,2019-01-03 00:00:00,955,9,17,$510.17
3,3,4,2019-01-03 00:00:00,577,19,3,$68.49
4,4,5,2019-01-03 00:00:00,429,8,18,$759.42

coustomars or purchases ko marge kerna hai

In [ ]:
merge_df=pd.merge(coustomars_df,purchases_df,on='id',how='inner')
merge_df

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Unnamed: 0,purch_date,customer_num,product_num,amount,paid
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,0,2019-01-03 00:00:00,823,27,12,$568.92
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,1,2019-01-03 00:00:00,606,28,14,$395.36
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,2,2019-01-03 00:00:00,955,9,17,$510.17
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,3,2019-01-03 00:00:00,577,19,3,$68.49
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,4,2019-01-03 00:00:00,429,8,18,$759.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0,995,2019-06-04 00:00:00,198,20,7,$609.35
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0,996,2019-06-04 00:00:00,96,27,14,$663.74
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0,997,2019-06-04 00:00:00,181,7,2,$27.66
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0,998,2019-06-04 00:00:00,951,54,4,$87.68
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0,999,2019-06-04 00:00:00,435,20,18,"$1,143.90"

provide to avrage company cost per company=> eska matlab hota ai copmpy me niklane jaankaridena gruby or mean ke jariye

In [ ]:
grouped_by_company = products_df.groupby('company')

In [ ]:
average_cost = grouped_by_company['cost'].mean()

In [ ]:
display(average_cost)

company
Aibox           56.330
Babbleopia      63.980
Brainsphere     22.830
Browsezoom      41.050
Cogibox         51.135
Digitube         8.550
Dynabox         99.400
Dynazzy         85.740
Eare            87.390
Eazzy           74.280
Edgeclub        40.690
Eimbee          98.740
Fanoodle        68.630
Flipstorm       37.790
Fliptune        75.320
Gevee           62.600
Innojam         73.700
Jabbersphere    30.670
Linkbuzz        95.680
Livepath        94.105
Meemm           65.350
Meevee          30.010
Meezzy          21.470
Muxo            92.330
Mynte           21.980
Ntag            60.585
Oloo            13.830
Oodoo           37.450
Oozz            42.190
Photofeed       42.560
Photojam        68.160
Photolist       59.230
Quatz           13.830
Quinu           41.220
Realcube        90.480
Realpoint       61.990
Skiba           36.670
Skinder         84.200
Skipfire         6.360
Skyble          99.540
Thoughtstorm    45.770
Topiclounge     74.060
Trunyx          87.050
Twitterworks    19.900
Vitz            22.695
Voonder         82.220
Wordware        87.510
Yakijo          73.050
Zazio           20.530
Zoombox         16.270
Name: cost, dtype: float64

pivot table ka matlab hota hai data ko acche trah se nichodna

In [ ]:
data={
    'region':['east','west','east','west','east','west'],
    'products':['A','B','C','D','E','F'],
    'sales':[100,200,300,400,500,600]
}

In [ ]:
df=pd.DataFrame(data)

pivot_table = df.pivot_table(values='sales',index='region',columns='products',aggfunc='sum')
display(pivot_table)

products      A      B      C      D      E      F
region
east      100.0    NaN  300.0    NaN  500.0    NaN
west        NaN  200.0    NaN  400.0    NaN  600.0

In [ ]:
data={
    'region':['east','west','east','west','east','west','esat','west'],
    'products':['A','B','C','D','E','F','g','h'],
    'sales': [100, 150, 200, 250, 300, 350, 200, 100]
}
df=pd.DataFrame(data)

pivot_table = df.pivot_table(values='sales',index='region',columns='products',aggfunc='sum',fill_value=0)
pivot_table

products    A    B    C    D    E    F    g    h
region
east      100    0  200    0  300    0    0    0
esat        0    0    0    0    0    0  200    0
west        0  150    0  250    0  350    0  100

In [ ]:
data = {
    'region': ['east', 'west', 'east', 'west', 'east', 'west', 'east', 'east'],
    'product': ['A', 'A', 'B', 'B', 'C', 'C', 'A', 'D'],
    'sales': [100, 150, 200, 250, 300, 350, 200, 100]
}

df = pd.DataFrame(data)

pivot_table = df.pivot_table(values='sales', index='region', columns='product', aggfunc='sum', fill_value=0)
pivot_table

product    A    B    C    D
region
east     300  200  300  100
west     150  250  350    0

In [ ]:
data = {
    'region': ['east', 'west'],
    'product1': [100, 150],
    'product2': [200, 250],
    'product3': [300, 350]
}

df = pd.DataFrame(data)

#melt the dataframe
melted_df = pd.melt(df, id_vars=['region'], value_vars=['product1', 'product2', 'product3'], var_name='product', value_name='sales')
print(melted_df)

  region   product  sales
0   east  product1    100
1   west  product1    150
2   east  product2    200
3   west  product2    250
4   east  product3    300
5   west  product3    350

In [ ]:

 purchases_df.to_excel('purchases_v1.xlsx', index=False)
 products_df.to_excel('products_v1.xlsx', index=False)